[tool.poetry]
name = "demo"
version = "0.1.0"
description = "A demo project for PR-Pilot-AI"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
