[build-system]
requires = ["setuptools>=42", "wheel"]

[project]
name = "game-of-life"
version = "0.1.0"
description = "A simple implementation of Conway's Game of Life"

[project.dependencies]
numpy = "1.26.4"
matplotlib = "3.8.3"
