apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pr-pilot-worker
spec:
  serviceName: pr-pilot-worker
  replicas: 2
  selector:
    matchLabels:
      app: pr-pilot
      tier: worker
  template:
    metadata:
      labels:
        app: pr-pilot
        tier: worker
    spec:
      containers:
      - name: worker
        image: {{ .Values.image.worker }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        resources:
          limits:
            memory: "500Mi"
            cpu: "1"
          requests:
            memory: "200Mi"
            cpu: "0.2"
        command: ["python", "manage.py"]
        args: ["run_task_worker"]
        env:
        - name: GITHUB_APP_PRIVATE_KEY_PATH
          value: "/etc/ssl/certs/github_private_key.pem"
        - name: REDIS_HOST
          value: "pr-pilot-redis-master.default.svc.cluster.local"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pr-pilot-db-postgresql
              key: postgres-password
        envFrom:
        - secretRef:
            name: pr-pilot-secret
        volumeMounts:
          - name: pem-volume
            mountPath: /etc/ssl/certs/github_private_key.pem
            subPath: github_app_private_key.pem
          - name: repo-cache
            mountPath: /repo_cache
      volumes:
      - name: pem-volume
        secret:
          secretName: pr-pilot-private-key
  volumeClaimTemplates:
  - metadata:
      name: repo-cache
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi