name: 📅 Daily Report

# Trigger only manually

on:
#  schedule:
#    # Run midnight PST
#    - cron: "0 8 * * *"
  workflow_dispatch:
    inputs: {}


jobs:
  daily-report:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grants write permissions to the `GITHUB_TOKEN`

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install pr-pilot-cli
      run: pip install --upgrade pr-pilot-cli

    - name: Run daily report script
      env:
        PR_PILOT_API_KEY: ${{ secrets.PR_PILOT_API_KEY }}
      run: |
        cd daily-report
        ./run.sh

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "PR Pilot"
        git config --global user.email "bot@pr-pilot.ai"
        git add .
        git commit -m "Daily Report $(date +'%Y-%m-%d')"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/PR-Pilot-AI/demo.git main
